export interface ModelResult {
  Dataset: string;
  Model: string;
  ImageSize: string;
  Manufacturer: string;
  'Experiment Type': string;
  Class: string;
  Precision: number;
  'Recall (Sensitivity)': number;
  Specificity: number;
  'F1-score': number;
  Support: number;
}

export const data: ModelResult[] = [
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "224x224",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - East and Southeast",
    Precision: 0.71,
    "Recall (Sensitivity)": 0.77,
    Specificity: 0.84,
    "F1-score": 0.74,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "224x224",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - South",
    Precision: 0.58,
    "Recall (Sensitivity)": 0.48,
    Specificity: 0.83,
    "F1-score": 0.53,
    Support: 1493
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "224x224",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "White",
    Precision: 0.63,
    "Recall (Sensitivity)": 0.68,
    Specificity: 0.8,
    "F1-score": 0.65,
    Support: 1497
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - East and Southeast",
    Precision: 0.73,
    "Recall (Sensitivity)": 0.84,
    Specificity: 0.84,
    "F1-score": 0.78,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - South",
    Precision: 0.67,
    "Recall (Sensitivity)": 0.56,
    Specificity: 0.86,
    "F1-score": 0.61,
    Support: 1493
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "White",
    Precision: 0.72,
    "Recall (Sensitivity)": 0.73,
    Specificity: 0.86,
    "F1-score": 0.72,
    Support: 1497
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "1024x1024",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - East and Southeast",
    Precision: 0.74,
    "Recall (Sensitivity)": 0.83,
    Specificity: 0.84,
    "F1-score": 0.78,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "1024x1024",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - South",
    Precision: 0.69,
    "Recall (Sensitivity)": 0.58,
    Specificity: 0.86,
    "F1-score": 0.63,
    Support: 1493
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "1024x1024",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "White",
    Precision: 0.72,
    "Recall (Sensitivity)": 0.75,
    Specificity: 0.86,
    "F1-score": 0.74,
    Support: 1497
  },
  {
    Dataset: "Mammo",
    Model: "DINOv2",
    ImageSize: "224x224",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - East and Southeast",
    Precision: 0.63,
    "Recall (Sensitivity)": 0.87,
    Specificity: 0.74,
    "F1-score": 0.73,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "DINOv2",
    ImageSize: "224x224",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - South",
    Precision: 0.74,
    "Recall (Sensitivity)": 0.23,
    Specificity: 0.96,
    "F1-score": 0.35,
    Support: 1493
  },
  {
    Dataset: "Mammo",
    Model: "DINOv2",
    ImageSize: "224x224",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "White",
    Precision: 0.6,
    "Recall (Sensitivity)": 0.77,
    Specificity: 0.74,
    "F1-score": 0.67,
    Support: 1497
  },
  {
    Dataset: "Mammo",
    Model: "DINOv2",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - East and Southeast",
    Precision: 0.75,
    "Recall (Sensitivity)": 0.71,
    Specificity: 0.88,
    "F1-score": 0.73,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "DINOv2",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - South",
    Precision: 0.58,
    "Recall (Sensitivity)": 0.59,
    Specificity: 0.79,
    "F1-score": 0.58,
    Support: 1493
  },
  {
    Dataset: "Mammo",
    Model: "DINOv2",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "White",
    Precision: 0.65,
    "Recall (Sensitivity)": 0.67,
    Specificity: 0.82,
    "F1-score": 0.66,
    Support: 1497
  },
  {
    Dataset: "Mammo",
    Model: "DINOv2",
    ImageSize: "1024x1024",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - East and Southeast",
    Precision: 0.64,
    "Recall (Sensitivity)": 0.88,
    Specificity: 0.76,
    "F1-score": 0.74,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "DINOv2",
    ImageSize: "1024x1024",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - South",
    Precision: 0.66,
    "Recall (Sensitivity)": 0.49,
    Specificity: 0.88,
    "F1-score": 0.56,
    Support: 1493
  },
  {
    Dataset: "Mammo",
    Model: "DINOv2",
    ImageSize: "1024x1024",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "White",
    Precision: 0.7,
    "Recall (Sensitivity)": 0.62,
    Specificity: 0.87,
    "F1-score": 0.66,
    Support: 1497
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "Without GE",
    "Experiment Type": "Original Data",
    Class: "Asian - East and Southeast",
    Precision: 0.72,
    "Recall (Sensitivity)": 0.8,
    Specificity: 0.85,
    "F1-score": 0.76,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "Without GE",
    "Experiment Type": "Original Data",
    Class: "Asian - South",
    Precision: 0.66,
    "Recall (Sensitivity)": 0.51,
    Specificity: 0.87,
    "F1-score": 0.57,
    Support: 1494
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "Without GE",
    "Experiment Type": "Original Data",
    Class: "White",
    Precision: 0.68,
    "Recall (Sensitivity)": 0.75,
    Specificity: 0.82,
    "F1-score": 0.72,
    Support: 1496
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Random Patching",
    Class: "Asian - East and Southeast",
    Precision: 0.59,
    "Recall (Sensitivity)": 0.66,
    Specificity: 0.77,
    "F1-score": 0.62,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Random Patching",
    Class: "Asian - South",
    Precision: 0.46,
    "Recall (Sensitivity)": 0.48,
    Specificity: 0.48,
    "F1-score": 0.47,
    Support: 1493
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Random Patching",
    Class: "White",
    Precision: 0.53,
    "Recall (Sensitivity)": 0.45,
    Specificity: 0.45,
    "F1-score": 0.49,
    Support: 1497
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "Without GE",
    "Experiment Type": "Random Patching",
    Class: "Asian - East and Southeast",
    Precision: 0.56,
    "Recall (Sensitivity)": 0.7,
    Specificity: 0.73,
    "F1-score": 0.62,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "Without GE",
    "Experiment Type": "Random Patching",
    Class: "Asian - South",
    Precision: 0.48,
    "Recall (Sensitivity)": 0.36,
    Specificity: 0.81,
    "F1-score": 0.41,
    Support: 1494
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "Without GE",
    "Experiment Type": "Random Patching",
    Class: "White",
    Precision: 0.49,
    "Recall (Sensitivity)": 0.5,
    Specificity: 0.74,
    "F1-score": 0.49,
    Support: 1496
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "256x256",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "Asian - East and Southeast",
    Precision: 0.51,
    "Recall (Sensitivity)": 0.69,
    Specificity: 0.66,
    "F1-score": 0.58,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "256x256",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "Asian - South",
    Precision: 0.45,
    "Recall (Sensitivity)": 0.4,
    Specificity: 0.75,
    "F1-score": 0.42,
    Support: 1493
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "256x256",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "White",
    Precision: 0.53,
    "Recall (Sensitivity)": 0.39,
    Specificity: 0.82,
    "F1-score": 0.45,
    Support: 1497
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "Asian - East and Southeast",
    Precision: 0.53,
    "Recall (Sensitivity)": 0.72,
    Specificity: 0.69,
    "F1-score": 0.61,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "Asian - South",
    Precision: 0.48,
    "Recall (Sensitivity)": 0.39,
    Specificity: 0.79,
    "F1-score": 0.43,
    Support: 1493
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "White",
    Precision: 0.54,
    "Recall (Sensitivity)": 0.45,
    Specificity: 0.8,
    "F1-score": 0.49,
    Support: 1497
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "768x768",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "Asian - East and Southeast",
    Precision: 0.65,
    "Recall (Sensitivity)": 0.72,
    Specificity: 0.8,
    "F1-score": 0.68,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "768x768",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "Asian - South",
    Precision: 0.53,
    "Recall (Sensitivity)": 0.5,
    Specificity: 0.77,
    "F1-score": 0.51,
    Support: 1493
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "768x768",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "White",
    Precision: 0.61,
    "Recall (Sensitivity)": 0.57,
    Specificity: 0.82,
    "F1-score": 0.59,
    Support: 1497
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "1024x1024",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "Asian - East and Southeast",
    Precision: 0.7,
    "Recall (Sensitivity)": 0.68,
    Specificity: 0.85,
    "F1-score": 0.69,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "1024x1024",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "Asian - South",
    Precision: 0.53,
    "Recall (Sensitivity)": 0.54,
    Specificity: 0.76,
    "F1-score": 0.53,
    Support: 1493
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "1024x1024",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "White",
    Precision: 0.59,
    "Recall (Sensitivity)": 0.6,
    Specificity: 0.79,
    "F1-score": 0.6,
    Support: 1497
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "Without GE",
    "Experiment Type": "Tissue-Only",
    Class: "Asian - East and Southeast",
    Precision: 0.58,
    "Recall (Sensitivity)": 0.7,
    Specificity: 0.75,
    "F1-score": 0.64,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "Without GE",
    "Experiment Type": "Tissue-Only",
    Class: "Asian - South",
    Precision: 0.48,
    "Recall (Sensitivity)": 0.38,
    Specificity: 0.79,
    "F1-score": 0.43,
    Support: 1494
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "Without GE",
    "Experiment Type": "Tissue-Only",
    Class: "White",
    Precision: 0.52,
    "Recall (Sensitivity)": 0.51,
    Specificity: 0.76,
    "F1-score": 0.51,
    Support: 1496
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Segmentation Map",
    Class: "Asian - East and Southeast",
    Precision: 0.58,
    "Recall (Sensitivity)": 0.83,
    Specificity: 0.7,
    "F1-score": 0.68,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Segmentation Map",
    Class: "Asian - South",
    Precision: 0.52,
    "Recall (Sensitivity)": 0.29,
    Specificity: 0.87,
    "F1-score": 0.37,
    Support: 1494
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Segmentation Map",
    Class: "White",
    Precision: 0.54,
    "Recall (Sensitivity)": 0.55,
    Specificity: 0.76,
    "F1-score": 0.54,
    Support: 1496
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "Without GE",
    "Experiment Type": "Segmentation Map",
    Class: "Asian - East and Southeast",
    Precision: 0.63,
    "Recall (Sensitivity)": 0.78,
    Specificity: 0.76,
    "F1-score": 0.7,
    Support: 1503
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "Without GE",
    "Experiment Type": "Segmentation Map",
    Class: "Asian - South",
    Precision: 0.52,
    "Recall (Sensitivity)": 0.34,
    Specificity: 0.84,
    "F1-score": 0.41,
    Support: 1494
  },
  {
    Dataset: "Mammo",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "Without GE",
    "Experiment Type": "Segmentation Map",
    Class: "White",
    Precision: 0.54,
    "Recall (Sensitivity)": 0.59,
    Specificity: 0.75,
    "F1-score": 0.56,
    Support: 1496
  },
  {
    Dataset: "BDen",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - East and Southeast",
    Precision: 0.72,
    "Recall (Sensitivity)": 0.77,
    Specificity: 0.77,
    "F1-score": 0.75,
    Support: 1405
  },
  {
    Dataset: "BDen",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "Asian - South",
    Precision: 0.66,
    "Recall (Sensitivity)": 0.55,
    Specificity: 0.55,
    "F1-score": 0.6,
    Support: 1465
  },
  {
    Dataset: "BDen",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Original Data",
    Class: "White",
    Precision: 0.68,
    "Recall (Sensitivity)": 0.75,
    Specificity: 0.82,
    "F1-score": 0.71,
    Support: 1448
  },
  {
    Dataset: "BDen",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Random Patching",
    Class: "Asian - East and Southeast",
    Precision: 0.6,
    "Recall (Sensitivity)": 0.69,
    Specificity: 0.69,
    "F1-score": 0.64,
    Support: 1405
  },
  {
    Dataset: "BDen",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Random Patching",
    Class: "Asian - South",
    Precision: 0.53,
    "Recall (Sensitivity)": 0.43,
    Specificity: 0.43,
    "F1-score": 0.48,
    Support: 1465
  },
  {
    Dataset: "BDen",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Random Patching",
    Class: "White",
    Precision: 0.52,
    "Recall (Sensitivity)": 0.54,
    Specificity: 0.75,
    "F1-score": 0.53,
    Support: 1448
  },
  {
    Dataset: "BDen",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "Asian - East and Southeast",
    Precision: 0.63,
    "Recall (Sensitivity)": 0.65,
    Specificity: 0.84,
    "F1-score": 0.64,
    Support: 1405
  },
  {
    Dataset: "BDen",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "Asian - South",
    Precision: 0.56,
    "Recall (Sensitivity)": 0.39,
    Specificity: 0.81,
    "F1-score": 0.46,
    Support: 1465
  },
  {
    Dataset: "BDen",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Tissue-Only",
    Class: "White",
    Precision: 0.51,
    "Recall (Sensitivity)": 0.66,
    Specificity: 0.69,
    "F1-score": 0.58,
    Support: 1448
  },
  {
    Dataset: "BDen",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Segmentation Map",
    Class: "Asian - East and Southeast",
    Precision: 0.65,
    "Recall (Sensitivity)": 0.7,
    Specificity: 0.82,
    "F1-score": 0.67,
    Support: 1405
  },
  {
    Dataset: "BDen",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Segmentation Map",
    Class: "Asian - South",
    Precision: 0.47,
    "Recall (Sensitivity)": 0.44,
    Specificity: 0.74,
    "F1-score": 0.45,
    Support: 1465
  },
  {
    Dataset: "BDen",
    Model: "EfficientNetB3",
    ImageSize: "512x512",
    Manufacturer: "All",
    "Experiment Type": "Segmentation Map",
    Class: "White",
    Precision: 0.52,
    "Recall (Sensitivity)": 0.51,
    Specificity: 0.76,
    "F1-score": 0.52,
    Support: 1448
  }
];